### ISSUE TITLE
Sort Query is not returning result as expected.

### ISSUE THREAD

**Issue by harshalizode** [dymmond/mongoz#33] opened 2024-05-06 13:05 UTC
### Discussed in https://github.com/tarsil/mongoz/discussions/32

<div type='discussions-op-text'>

<sup>Originally posted by **harshalizode** May  6, 2024</sup>
Hello, 

I have the Permission Model as:
```
class Permission(mongoz.Document):
    idx: int = mongoz.Integer()
    code: str = mongoz.String()
```
I am trying to sort the permissions in Ascending order.
` await Permission.objects.sort("idx", Order.ASCENDING).values(["idx"])`

But I am getting the result as
![sort issue](https://github.com/tarsil/mongoz/assets/66934194/1ef8817c-26f5-49a3-acc7-e2b02e5a183f)

Can you confirm that this is an issue or a mistake that occurred while running the query?
Thank you.</div>

**Comment by tarsil** [comment] 2024-05-06 14:30
@harshalizode it seems like a regression because here 

https://github.com/tarsil/mongoz/blob/main/tests/models/manager/test_sort.py

We have it working. Maybe something needs to be updated/fixed on the values() side.

I will need to run some proper testing

**Comment by harshalizode** [comment] 2024-05-07 03:50
I want to sort basis on the integer value that starts with 1 upto 1000, for the string its working.

**Comment by tarsil** [comment] 2024-06-04 21:40
@harshalizode this should be addressed this week btw

**Comment by harshalizode** [comment] 2024-06-06 04:13
Okay, have you released the version for it?

**Comment by tarsil** [comment] 2024-06-06 21:05
@harshalizode we had some issues with the API for the release but it should be released soon. No worries.

**Comment by harshalizode** [comment] 2024-06-07 03:52
Okay, I will wait.

**Comment by tarsil** [comment] 2024-06-11 16:38
@harshalizode I actually ran the example and I'm not having this issue. So I did in two way for an example. See below.

```python
class Movie(Document):
    idx: str = mongoz.Integer()

    class Meta:
        registry = client
        database = "test_db"
```

This is my document

These are my tests, passing:

```python
async def test_model_sort_asc() -> None:
    for i in range(10):
        await Movie.objects.create(idx=i)

    movies = await Movie.objects.sort(idx__asc=True).values_list(["idx"], flat=True)

    assert movies == [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


async def test_model_sort_desc() -> None:
    for i in range(10):
        await Movie.objects.create(idx=i)

    movies = await Movie.objects.sort(idx__desc=True).values_list(["idx"], flat=True)

    assert movies == [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


async def test_model_sort_asc_obj() -> None:
    for i in range(10):
        await Movie.objects.create(idx=i)

    movies = await Movie.objects.sort("idx", Order.ASCENDING).values_list(["idx"], flat=True)

    assert movies == [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


async def test_model_sort_obj() -> None:
    for i in range(10):
        await Movie.objects.create(idx=i)

    movies = await Movie.objects.sort("idx", Order.DESCENDING).values_list(["idx"], flat=True)

    assert movies == [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

```

For `values`.

```python
async def test_model_sort_asc() -> None:
    for i in range(10):
        await Movie.objects.create(idx=i)

    movies = await Movie.objects.sort(idx__asc=True).values(["idx"])

    assert movies == [
        {"idx": 0},
        {"idx": 1},
        {"idx": 2},
        {"idx": 3},
        {"idx": 4},
        {"idx": 5},
        {"idx": 6},
        {"idx": 7},
        {"idx": 8},
        {"idx": 9},
    ]


async def test_model_sort_desc() -> None:
    for i in range(10):
        await Movie.objects.create(idx=i)

    movies = await Movie.objects.sort(idx__desc=True).values(["idx"])

    assert movies == [
        {"idx": 9},
        {"idx": 8},
        {"idx": 7},
        {"idx": 6},
        {"idx": 5},
        {"idx": 4},
        {"idx": 3},
        {"idx": 2},
        {"idx": 1},
        {"idx": 0},
    ]


async def test_model_sort_asc_obj() -> None:
    for i in range(10):
        await Movie.objects.create(idx=i)

    movies = await Movie.objects.sort("idx", Order.ASCENDING).values(["idx"])

    assert movies == [
        {"idx": 0},
        {"idx": 1},
        {"idx": 2},
        {"idx": 3},
        {"idx": 4},
        {"idx": 5},
        {"idx": 6},
        {"idx": 7},
        {"idx": 8},
        {"idx": 9},
    ]


async def test_model_sort_obj() -> None:
    for i in range(10):
        await Movie.objects.create(idx=i)

    movies = await Movie.objects.sort("idx", Order.DESCENDING).values(["idx"])

    assert movies == [
        {"idx": 9},
        {"idx": 8},
        {"idx": 7},
        {"idx": 6},
        {"idx": 5},
        {"idx": 4},
        {"idx": 3},
        {"idx": 2},
        {"idx": 1},
        {"idx": 0},
    ]

```

The only difference is that you are using the `using` and that might be the problem. So, I'm updating that now to return managers internally and will do a release and you can try again.

**Comment by harshalizode** [comment] 2024-06-12 05:40
Yes, it has been resolved, and I am receiving the expected solution.
Thank you.

**Comment by tarsil** [comment] 2024-06-12 06:55
Great. I will close the issue then @harshalizode 👍🏼

**Closed by tarsil** 2024-06-12 06:55 UTC

**Comment by harshalizode** [comment] 2024-06-12 11:27
Okay, Thank you.
